### PR TITLE
LEST update

### PR DESCRIPTION
**Pull request by fborges22**
Recently, I updated the LEST inside the project and made some changes to grant compatibility with GCC 4.8.5

### CODE REVIEW

**Comment by fborges22** [comment]
Updated the LEST and also added compatibility with GCC 4.8.5 of RHEL7

**Comment by pulzed** [comment]
Sorry, not a big enough change to merit a pull and a copyright addition. I intend to update most of these myself before the 1.0.0 version - sorry.

**Comment by fborges22** [comment]
Hi Danijel,

OK. Thank you for reviewing my pull request. If possible I would like to
help you to develop the 1.0.0 version. Is there anything I can do to help?
I found your mINI parser a really nice project and I loved it :D

Best regards,
F.Borges

**Comment by pulzed** [comment]
Hey - thank you for the interest. I was actually looking into rewriting the INIWriter class because while the code works it is somewhat of a mess, and could use a more sane rewrite. Some benchmarks wouldn't hurt either. Other stuff is mostly ok.

**Comment by fborges22** [comment]
Hey Danijel,

OK. I will analyze the performance of the INIWriter class algorithm and try
to improve the current implementation to be faster. In addition, I will
implement that feature, which I mentioned earlier, where the INIStructure
can write to a std::string.

When I complete those implementations I will contact you.

Best regards,
F.Borges

**Comment by pulzed** [comment]
Thanks!
-Danijel

**Pull request closed without merging**
