### PR TITLE
Added support comment to the right value

### PR DESCRIPTION
**Pull request by Perchik71**
I didn't quite understand github , I only added 3 lines

### CODE REVIEW

**Comment by pulzed** [comment]
Hi - thank you for your effort, however - I specifically implemented this library to not allow comments on value lines so that semicolon characters can be part of a value. Your implementation would break my own projects and potentially other projects depending on this library as well - sorry. I went through this thought process as I was implementing the library and there is no good reason to allow comments on value lines, traditionally INI files have only whole-line comments, and if you want to comment on a value you do it one line above it. And yes you could escape the semicolons in values too, but that would actually be worse for the API users and more confusing in the spec.

**Comment by pulzed** [comment]
Also - if you really need value-line comments, you could do it outside the library, simply removing anything past ; in your values as you fetch them (you could even make a small wrapper so it happens invisibly).

**Comment by Perchik71** [comment]
Hello, I did just that. I made myself a Fork. I needed a library, for reading and writing INI, without WinAPI. In addition, it replaced the previous library, which could only read.

**Comment by pulzed** [comment]
That's perfectly fine - good luck!

**Pull request closed without merging**
